---
title: "police_data_binding"
author: "Tram Anh Hoang"
date: "2023-01-25"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(rio)
library(here)
library(readxl)
library(dplyr)
library(data.table)
library(janitor)
```

# Read spec files

```{r read-spec, eval=FALSE, echo=FALSE}

#For the years 2006-2016
spec2006 <- read_excel(here("data", "police_data", "spec-files", "2006-spec.xlsx"),
                       skip=3) %>% select(1,3,4) %>% clean_names()
spec2007 <- read_excel(here("data", "police_data", "spec-files", "2007-spec.xlsx"),
                       skip=3) %>% select(1,3,4) %>% clean_names()
spec2008 <- read_excel(here("data", "police_data", "spec-files", "2008-spec.xlsx"),
                       skip=3) %>% select(1,3,4)%>% clean_names()
spec2009 <- read_excel(here("data", "police_data", "spec-files", "2009-spec.xlsx"),
                       skip=3) %>% select(1,3,4) %>% clean_names()
spec2010 <- read_excel(here("data", "police_data", "spec-files", "2010-spec.xlsx"),
                       skip=3) %>% select(1,3,4) %>% clean_names()
spec2011 <- read_excel(here("data", "police_data", "spec-files", "2011-spec.xlsx"),
                       skip=3) %>% select(1,3,4) %>% clean_names()
spec2012 <- read_excel(here("data", "police_data", "spec-files", "2012-spec.xlsx"),
                       skip=3) %>% select(1,3,4) %>% clean_names()
spec2013 <- read_excel(here("data", "police_data", "spec-files", "2013-spec.xlsx"),
                       skip=3) %>% select(1,3,4) %>% clean_names()
spec2014 <- read_excel(here("data", "police_data", "spec-files", "2014-spec.xlsx"),
                       skip=3) %>% select(1,3,4) %>% clean_names()
spec2015 <- read_excel(here("data", "police_data", "spec-files", "2015-spec.xlsx"),
                       skip=3) %>% select(1,3,4) %>% clean_names()
spec2016 <- read_excel(here("data", "police_data", "spec-files", "2016-spec.xlsx"),
                       skip=3) %>% select(1,3,4) %>% clean_names()

#For the years 2017-2021
spec2017 <- read_excel(here("data", "police_data", "spec-files", "2017-spec.xlsx"),
                       skip=3) %>% select(1) %>% clean_names()
spec2018 <- read_excel(here("data", "police_data", "spec-files", "2018-spec.xlsx"),
                       skip=0) %>% select(1) %>% clean_names() 
names(spec2018)[names(spec2018)=="stop_question_and_frisk_stop_question_and_frisk_trespass"] <- "variable_label"

spec2019 <- read_excel(here("data", "police_data", "spec-files", "2019-spec.xlsx"),
                       skip=3) %>% select(1) %>% clean_names()

```

# Join spec files to get a full list of variables

```{r, eval=FALSE, echo=FALSE}
#For the years 2006-2016
spec2006to2016 <- list(spec2006, spec2007, spec2008, spec2009, spec2010, spec2011, spec2012, spec2013, spec2014, spec2015, spec2016) %>%
                  reduce(full_join)
write_csv(spec2006to2016, here("data", "police_data", "spec-files", "2006to2016-spec.csv"))

#For the years 2017-2021
spec2017to2019 <- list(spec2017, spec2018, spec2019) %>%
                  reduce(full_join)
write_csv(spec2017to2019, here("data", "police_data", "spec-files", "2017to2019-spec.csv"))
```


# Read police search frisk data from 2006 to 2021

```{r, eval=FALSE, echo=FALSE}
#Using for loop - not working
filenames0616 <- list.files(path = here("data", "police_data"),
                            pattern="20[0-9]{2}.csv",
                            full.names=TRUE)

filenames1721 <- list.files(path = here("data", "police_data"),
                            pattern="20[0-9]{2}.xlsx",
                            full.names=TRUE)
c1 <- c("06", "07","08","09","10","11","12","13","14","15","16")

for(i in c1) {                              
  assign(paste0("p20", i),                                   
         read.csv(here("data", "police_data","p20[i]{1}.csv")) %>% clean_names())
}
```


```{r read}
p2006 <- read.csv(here("data", "police_data", "2006.csv"))%>% clean_names()
p2007 <- read.csv(here("data", "police_data", "2007.csv"))%>% clean_names()
p2008 <- read.csv(here("data", "police_data", "2008.csv"))%>% clean_names()
p2009 <- read.csv(here("data", "police_data", "2009.csv"))%>% clean_names()
p2010 <- read.csv(here("data", "police_data", "2010.csv"))%>% clean_names()
p2011 <- read.csv(here("data", "police_data", "2011.csv"))%>% clean_names()
p2012 <- read.csv(here("data", "police_data", "2012.csv"))%>% clean_names()
p2013 <- read.csv(here("data", "police_data", "2013.csv"))%>% clean_names()
p2014 <- read.csv(here("data", "police_data", "2014.csv"))%>% clean_names()
p2015 <- read.csv(here("data", "police_data", "sqf-2015.csv"))%>% clean_names()
p2016 <- read.csv(here("data", "police_data", "sqf-2016.csv"))%>% clean_names()
p2017 <- read_excel(here("data", "police_data", "sqf-2017.xlsx"))%>% clean_names()
p2018 <- read_excel(here("data", "police_data", "sqf-2018.xlsx")) %>% clean_names()
p2019 <- read_excel(here("data", "police_data", "sqf-2019.xlsx"))%>% clean_names()
p2020 <- read_excel(here("data", "police_data", "sqf-2020.xlsx"))%>% clean_names()
p2021 <- read_excel(here("data", "police_data", "sqf-2021.xlsx"))%>% clean_names()
```

# Bind datasets together and export for later use
```{r bind_data}
#For the years 2006-2016
p2006to2016 <- rbindlist(list(p2006,p2007,p2008,p2009,p2010,p2011,p2012,p2013,p2014,p2015,p2016),
                         fill=TRUE)

#For the years 2017-2021
p2017 <- p2017 %>% mutate(stop_frisk_date = as.character(stop_frisk_date),
                          stop_frisk_time = as.character(stop_frisk_time))
p2018 <- p2018 %>% mutate(stop_frisk_date = as.character(stop_frisk_date),
                          stop_frisk_time = as.character(stop_frisk_time))
p2019 <- p2019 %>% mutate(stop_frisk_date = as.character(stop_frisk_date),
                          stop_frisk_time = as.character(stop_frisk_time))
p2020 <- p2020 %>% mutate(stop_frisk_date = as.character(stop_frisk_date),
                          stop_frisk_time = as.character(stop_frisk_time))
p2021 <- p2021 %>% mutate(stop_frisk_date = as.character(stop_frisk_date),
                          stop_frisk_time = as.character(stop_frisk_time))

p2017to2021 <- rbindlist(list(p2017,p2018,p2019,p2020,p2021),
                         fill=TRUE)

#Export data to csv
write_csv(p2006to2016, here("data", "police_data", "combined data", "p2006to2016.csv"))
write_csv(p2017to2021, here("data", "police_data", "combined data", "p2017to2021.csv"))

```


# Select random rows to reduce the sizes of datasets
```{r}
sample_p0616 <- sample_n(p2006to2016, 110000)
sample_p1721 <- sample_n(p2017to2021, 50000)

write_csv(sample_p0616, here("data", "police_data", "random sample data", "sample_p0616.csv"))
write_csv(sample_p1721, here("data", "police_data", "random sample data", "sample_p1721.csv"))

```


# Select relevant variables and bind datasets together
```{r}
#Read in data
p0616 <- sample_p0616
p1721 <- sample_p1721

#Ommit unneeded columns & uniformize race labels
p0616 <- p0616 %>%
  select(year, race, frisked, searched, inout, xcoord, ycoord, zip,age) %>%
  mutate(race = fct_recode(race,"Asian/Pacific Islander"="A",
                                "Black"="B",
                                "American Indian/ Alaskan Native"="I",
                                "Black Hispanic" = "P",
                                "White Hispanic" = "Q",
                                "White"="W",
                                "Others"="Z",
                                "Others"="U"),
         age = as.integer(age),
         xcoord = as.integer(xcoord),
         ycoord = as.integer(ycoord))

p1721 <- p1721 %>%
  select(year2, suspect_race_description, frisked_flag, searched_flag, location_in_out_code, stop_location_x, stop_location_y, stop_location_zip_code, suspect_reported_age)
  
names(p1721) <- c("year", "race", "frisked", "searched", "inout", "xcoord", "ycoord", "zip", "age")

p1721 <- p1721 %>% 
  mutate(race = fct_recode(race,"Asian/Pacific Islander"="MIDDLE EASTERN/SOUTHWEST",
                                "Asian/Pacific Islander"="ASIAN / PACIFIC ISLANDER",
                                "Asian/Pacific Islander"="MIDDLE EASTERN/SOUTHWEST ASIAN",
                                "Asian/Pacific Islander"="ASIAN/PAC.ISL",
                                "Black"="BLACK",
                                "American Indian/ Alaskan Native"="AMERICAN INDIAN/ALASKAN NATIVE",
                                "American Indian/ Alaskan Native"="AMER IND",
                                "American Indian/ Alaskan Native"="AMERICAN INDIAN/ALASKAN N",
                                "Black Hispanic" = "BLACK HISPANIC",
                                "White Hispanic" = "WHITE HISPANIC",
                                "White"="WHITE",
                                "Unknown"="(null)",
                                "Unknown"="MALE"),
         age = as.integer(age),
         xcoord=as.integer(xcoord),
         ycoord=as.integer(ycoord))

#Bind data sets and export
p0621 <- bind_rows(p0616, p1721)
write_csv(p0621, here("data", "police_data", "dashboard data", "sample_p0621.csv"))

```

